#!/bin/bash

usage() {
    echo "Usage: $0 [option...]"
    echo ""
    echo "Application Options:"
    echo "  -c                            Command to execute (install or remove)"
    echo "  -p                            For install: full path to pkg, For remove: name of pkg"
}

command=""
package=""

while getopts c:p:u:vs opt
do
    case $opt in
        c)
            command=$OPTARG
            ;;
        p)
            package=$OPTARG
            ;;
   esac
done

if [ ! "$command" == "install" ] || [ -z "$package" ] ; then
    usage
    exit 1
fi

if [ ! -e $package ] ; then
   echo "Invalid package path"
   exit 1
fi

echo "status: starting"

basedir=/media/cryptofs

echo "status: unpacking"

echo "status: verifying"

package_id=$(/usr/bin/ar p $package  control.tar.gz | /bin/tar -O -z -x -f - ./control | /bin/sed -n -e 's/^Package: //p')

if [ -z "$package_id" ] ; then
   echo "Invalid package id"
   exit 1
fi

echo "status: installing $package_id"

opkg -o /media/cryptofs/apps -force-overwrite install $package

/usr/bin/pmServicePostInstall.sh

echo "status: done"
